# use the basic ubuntu container
FROM ubuntu:latest

# update container and install ssh
RUN apt-get update && apt-get install -y openssh-server
RUN sed -i 's/PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
ENTRYPOINT service ssh start && bash

# create new user with a temporary password
RUN useradd -ms /bin/bash guest
RUN echo "guest:123456" | chpasswd
